import { Metadata } from "next";
import Link from "next/link";
import { Radar, ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Pentra privacy policy. How we collect, use, and protect your data.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#08090E] text-[#F1F5F9]">
      {/* Nav */}
      <header className="border-b border-white/[0.06] bg-[#08090E]/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#0EA5E9]/[0.1]">
              <Radar className="h-4 w-4 text-[#0EA5E9]" />
            </div>
            <span className="text-[16px] font-bold tracking-tight">Pentra</span>
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-[14px] font-medium text-[#8B8FA3] transition-colors hover:text-white">
            <ArrowLeft className="h-3.5 w-3.5" /> Back
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Privacy Policy</h1>
        <p className="mt-2 text-sm text-[#8B8FA3]">Last updated: August 24, 2026</p>

        <div className="mt-10 space-y-8 text-[#94A3B8] leading-relaxed [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-[#F1F5F9] [&_h2]:mt-10 [&_h2]:mb-3 [&_h3]:font-semibold [&_h3]:text-[#F1F5F9] [&_h3]:mt-6 [&_h3]:mb-2 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-1">
          <p>
            Pentra (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) operates the pentra.dev website and platform. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service.
          </p>

          <h2>1. Information We Collect</h2>
          <h3>Account Information</h3>
          <p>When you create an account, we collect your name, email address, and authentication credentials through our third-party provider (Clerk).</p>

          <h3>Website Data</h3>
          <p>When you connect a website to Pentra, we collect:</p>
          <ul>
            <li>Your website domain and page content (via automated crawling)</li>
            <li>Site metadata, keywords, and niche information</li>
            <li>Brand identity data (colors, logo URL, fonts) extracted programmatically</li>
            <li>Publishing credentials (GitHub tokens, WordPress credentials, webhook URLs)</li>
          </ul>

          <h3>Generated Content</h3>
          <p>We store all articles, topic clusters, and metadata generated by our AI pipeline on your behalf.</p>

          <h3>Outreach Mailbox Data</h3>
          <p>When you separately connect a dedicated outreach mailbox, we store the OAuth credentials required for the outreach mode you choose. In manual mode, Pentra sends only a message that an owner separately approves and triggers. If authority autopilot is available, explicit, versioned tenant-level consent authorizes Pentra to send one verified initial outreach email and at most two timed follow-ups in the same provider thread for an eligible opportunity. Remaining follow-ups are cancelled after a reply, exact-recipient STOP request, hard bounce, verified link acquisition, tenant parking, consent withdrawal, or sender-configuration change. Disabling authority autopilot prevents new delivery claims, although a provider attempt already claimed before disablement may still settle once so Pentra can record its actual outcome; it cannot create a later sequence step after authorization changed.</p>
          <p>New Gmail connections do not grant Pentra permission to read your mailbox. Gmail OAuth is a consented-recipient-only channel: a public address listing, address discovery, or sender approval is not recipient consent. Before a Gmail message can be approved or sent, Pentra requires a current affirmative opt-in record for that recipient and binds its source, timestamp, purpose, and non-reversible evidence digest into the message&apos;s versioned policy receipt. Revocation or expiration invalidates unsent messages. Pentra stores the evidence digest, not the raw form, contract, request, registration, or relationship record.</p>
          <p>Before prospect sending is enabled, an owner-triggered fixed-recipient canary must prove that hard-bounce notifications for that exact mailbox reach the current audited receiving-only relay. Each outbound message uses an unguessable, message-specific reply address whose secret is independent from its outbound message identifier. The relay forwards signed, bodyless results for authenticated replies, structured hard bounces, and exact-recipient STOP requests. Pentra&apos;s application database never stores inbound MIME, attachments, subjects, or bodies: the audited receiving provider and adapter are configured to discard attachments and content after bounded transient classification, subject to the provider retention terms disclosed for the service. We retain only resulting status, bounded identifier digests, timestamps, suppression entries, replay keys, and non-reversible evidence digests. Existing connections that previously granted Gmail readonly access may continue bounded human-reply and exact-recipient opt-out monitoring until migration; that legacy path does not automatically suppress addresses from DSNs.</p>

          <h3>Payment Information</h3>
          <p>Payment processing is handled by Stripe through Clerk Billing. We do not store your credit card details directly. Stripe&apos;s privacy policy governs payment data handling.</p>

          <h2>2. How We Use Your Information</h2>
          <ul>
            <li>To crawl and analyze your website for content generation</li>
            <li>To generate keyword strategies and article content</li>
            <li>To fact-check generated content against web sources</li>
            <li>To publish articles to your connected platforms</li>
            <li>To deliver outreach you manually approve or explicitly authorize through tenant-level authority-autopilot consent, subject to recipient-level opt-in for Gmail OAuth, and to honor replies, bounces, consent revocation, and opt-out requests</li>
            <li>To manage your subscription and account</li>
            <li>To send you service-related notifications</li>
            <li>To improve service quality using operational telemetry and feedback that excludes Google Workspace or Gmail user data</li>
          </ul>

          <h2>3. Data Sharing</h2>
          <p>We share your data with the following third-party services, strictly for providing our service:</p>
          <ul>
            <li><strong className="text-[#F1F5F9]">Anthropic (Claude)</strong> — AI content generation and fact-checking</li>
            <li><strong className="text-[#F1F5F9]">OpenAI</strong> — web research, image generation, YouTube search</li>
            <li><strong className="text-[#F1F5F9]">Clerk</strong> — authentication and billing</li>
            <li><strong className="text-[#F1F5F9]">Convex</strong> — database and backend infrastructure</li>
            <li><strong className="text-[#F1F5F9]">Vercel</strong> — website hosting</li>
            <li><strong className="text-[#F1F5F9]">Stripe</strong> — payment processing (via Clerk)</li>
            <li><strong className="text-[#F1F5F9]">Google Workspace and Gmail APIs</strong> — only to provide mailbox features that you connect and explicitly request</li>
            <li><strong className="text-[#F1F5F9]">Inbound email relay provider</strong> — only to receive message-specific outreach replies and routed delivery-status notices, discard attachments/content under the audited retention configuration, and deliver signed receiving-only events to Pentra</li>
          </ul>
          <p>We do not sell your personal data to third parties.</p>

          <h2>4. Google API Limited Use</h2>
          <p>Pentra&apos;s use and transfer to any other app of information received from Google APIs adheres to the Google API Services User Data Policy, including its Limited Use requirements. Google Workspace and Gmail user data, including data derived from it, is used only to provide or improve the specific user-facing mailbox feature you request. It is never used to train, retrain, or improve a generalized or non-personalized AI or machine-learning model, and it is not used for advertising, profiling, credit decisions, or sale.</p>
          <p>Humans do not read Google Workspace, Gmail, or relayed inbound message content except when you give affirmative permission for a specific support or security investigation, when access is necessary to investigate abuse or a security incident, or when required by applicable law. Automated reply, structured-bounce, and opt-out classification is deterministic and bounded; Pentra&apos;s database stores only the status and bodyless digest receipts described above.</p>

          <h2>5. Data Retention</h2>
          <p>We retain account and site data while your account is active. Ordinary site deletion does not delete pseudonymous, account-wide outreach suppression and contact-cooldown records; they remain available to honor STOP requests and prevent duplicate contact if a site is recreated or another site in the account encounters the same recipient. You can request full-account deletion through the available account controls or by contacting us at pentrahelp@gmail.com. Once that request is verified, Pentra stops new automated execution, revokes stored publishing, search, and outreach credentials, and purges the account-wide suppression and contact-cooldown records through a bounded, resumable process after any already-claimed external operation settles.</p>
          <p>A non-reversible, global hashed sender reputation and pacing record may be unlinked from your account and retained for no more than 90 days across account deletion or sender transfer. This bounded safety record prevents deletion, transfer, or reconnect from resetting sender warm-up and pacing; it does not contain message content, a reusable credential, or retained site content. We may also retain or pseudonymize minimal billing, abuse-prevention, quota, and provider-spend receipts when required for legal, security, or accounting purposes.</p>

          <h2>6. Data Security</h2>
          <p>We implement industry-standard security measures to protect your data, including TLS encryption in transit and encryption at rest. Publishing credentials (GitHub tokens, WordPress passwords) are stored securely in our database and only accessed during the publishing process.</p>

          <h2>7. Your Rights</h2>
          <p>Under applicable data protection laws (including GDPR), you have the right to:</p>
          <ul>
            <li>Access your personal data</li>
            <li>Correct inaccurate data</li>
            <li>Request deletion of your data</li>
            <li>Export your data in a portable format</li>
            <li>Object to or restrict processing of your data</li>
            <li>Withdraw consent at any time</li>
          </ul>
          <p>To exercise these rights, contact us at pentrahelp@gmail.com.</p>

          <h2>8. Cookies</h2>
          <p>We use essential cookies only for authentication and session management. We do not use tracking cookies or third-party advertising cookies. Google Analytics may be used for anonymous usage statistics with your consent.</p>

          <h2>9. International Data Transfers</h2>
          <p>Your data may be processed in the United States and other countries where our service providers operate. We ensure appropriate safeguards are in place for international data transfers in accordance with GDPR requirements.</p>

          <h2>10. Children&apos;s Privacy</h2>
          <p>Pentra is not intended for use by individuals under 16 years of age. We do not knowingly collect personal data from children.</p>

          <h2>11. Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify you of material changes via email or through the service.</p>

          <h2>12. Contact Us</h2>
          <p>If you have questions about this Privacy Policy, contact us:</p>
          <div className="rounded-lg border border-white/[0.06] bg-[#0F1117] p-5 mt-3 text-[14px] space-y-1">
            <p><strong className="text-[#F1F5F9]">Email:</strong> pentrahelp@gmail.com</p>
            <p><strong className="text-[#F1F5F9]">Support:</strong> pentrahelp@gmail.com</p>
            <p><strong className="text-[#F1F5F9]">Phone:</strong> +49 1520 9530880</p>
            <p><strong className="text-[#F1F5F9]">Address:</strong> Pentra Legal Team</p>
            <p>Kerpener Straße 6, 50170 Kerpen, Germany</p>
          </div>
        </div>
      </main>
    </div>
  );
}
