import { Metadata } from "next";
import Link from "next/link";
import { Radar, ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Pentra privacy policy. How we collect, use, and protect your data.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#08090E] text-[#F1F5F9]">
      {/* Nav */}
      <header className="border-b border-white/[0.06] bg-[#08090E]/80 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-4xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#0EA5E9]/[0.1]">
              <Radar className="h-3.5 w-3.5 text-[#0EA5E9]" />
            </div>
            <span className="text-[14px] font-semibold tracking-tight">Pentra</span>
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-[13px] text-[#8B8FA3] transition-colors hover:text-white">
            <ArrowLeft className="h-3 w-3" /> Back
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Privacy Policy</h1>
        <p className="mt-2 text-sm text-[#8B8FA3]">Last updated: March 5, 2026</p>

        <div className="mt-10 space-y-8 text-[#94A3B8] leading-relaxed [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-[#F1F5F9] [&_h2]:mt-10 [&_h2]:mb-3 [&_h3]:font-semibold [&_h3]:text-[#F1F5F9] [&_h3]:mt-6 [&_h3]:mb-2 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-1">
          <p>
            Pentra (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) operates the pentra.dev website and platform. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service.
          </p>

          <h2>1. Information We Collect</h2>
          <h3>Account Information</h3>
          <p>When you create an account, we collect your name, email address, and authentication credentials through our third-party provider (Clerk).</p>

          <h3>Website Data</h3>
          <p>When you connect a website to Pentra, we collect:</p>
          <ul>
            <li>Your website domain and page content (via automated crawling)</li>
            <li>Site metadata, keywords, and niche information</li>
            <li>Brand identity data (colors, logo URL, fonts) extracted programmatically</li>
            <li>Publishing credentials (GitHub tokens, WordPress credentials, webhook URLs)</li>
          </ul>

          <h3>Generated Content</h3>
          <p>We store all articles, topic clusters, and metadata generated by our AI pipeline on your behalf.</p>

          <h3>Payment Information</h3>
          <p>Payment processing is handled by Stripe through Clerk Billing. We do not store your credit card details directly. Stripe&apos;s privacy policy governs payment data handling.</p>

          <h2>2. How We Use Your Information</h2>
          <ul>
            <li>To crawl and analyze your website for content generation</li>
            <li>To generate keyword strategies and article content</li>
            <li>To fact-check generated content against web sources</li>
            <li>To publish articles to your connected platforms</li>
            <li>To manage your subscription and account</li>
            <li>To send you service-related notifications</li>
            <li>To improve our AI models and service quality</li>
          </ul>

          <h2>3. Data Sharing</h2>
          <p>We share your data with the following third-party services, strictly for providing our service:</p>
          <ul>
            <li><strong className="text-[#F1F5F9]">Anthropic (Claude)</strong> — AI content generation and fact-checking</li>
            <li><strong className="text-[#F1F5F9]">OpenAI</strong> — web research, image generation, YouTube search</li>
            <li><strong className="text-[#F1F5F9]">Clerk</strong> — authentication and billing</li>
            <li><strong className="text-[#F1F5F9]">Convex</strong> — database and backend infrastructure</li>
            <li><strong className="text-[#F1F5F9]">Vercel</strong> — website hosting</li>
            <li><strong className="text-[#F1F5F9]">Stripe</strong> — payment processing (via Clerk)</li>
          </ul>
          <p>We do not sell your personal data to third parties.</p>

          <h2>4. Data Retention</h2>
          <p>We retain your data for as long as your account is active. You can request deletion of your account and all associated data by contacting us at pentrahelp@gmail.com. Upon account deletion, your data will be permanently removed within 30 days.</p>

          <h2>5. Data Security</h2>
          <p>We implement industry-standard security measures to protect your data, including TLS encryption in transit and encryption at rest. Publishing credentials (GitHub tokens, WordPress passwords) are stored securely in our database and only accessed during the publishing process.</p>

          <h2>6. Your Rights</h2>
          <p>Under applicable data protection laws (including GDPR), you have the right to:</p>
          <ul>
            <li>Access your personal data</li>
            <li>Correct inaccurate data</li>
            <li>Request deletion of your data</li>
            <li>Export your data in a portable format</li>
            <li>Object to or restrict processing of your data</li>
            <li>Withdraw consent at any time</li>
          </ul>
          <p>To exercise these rights, contact us at pentrahelp@gmail.com.</p>

          <h2>7. Cookies</h2>
          <p>We use essential cookies only for authentication and session management. We do not use tracking cookies or third-party advertising cookies. Google Analytics may be used for anonymous usage statistics with your consent.</p>

          <h2>8. International Data Transfers</h2>
          <p>Your data may be processed in the United States and other countries where our service providers operate. We ensure appropriate safeguards are in place for international data transfers in accordance with GDPR requirements.</p>

          <h2>9. Children&apos;s Privacy</h2>
          <p>Pentra is not intended for use by individuals under 16 years of age. We do not knowingly collect personal data from children.</p>

          <h2>10. Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify you of material changes via email or through the service.</p>

          <h2>11. Contact Us</h2>
          <p>If you have questions about this Privacy Policy, contact us:</p>
          <div className="rounded-lg border border-white/[0.06] bg-[#0F1117] p-5 mt-3 text-[14px] space-y-1">
            <p><strong className="text-[#F1F5F9]">Email:</strong> pentrahelp@gmail.com</p>
            <p><strong className="text-[#F1F5F9]">Support:</strong> pentrahelp@gmail.com</p>
            <p><strong className="text-[#F1F5F9]">Phone:</strong> +49 1520 9530880</p>
            <p><strong className="text-[#F1F5F9]">Address:</strong> Pentra Legal Team</p>
            <p>Kerpener Straße 6, 50170 Kerpen, Germany</p>
          </div>
        </div>
      </main>
    </div>
  );
}
