import { Metadata } from "next";
import Link from "next/link";
import { Radar, ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Pentra terms of service. Rules and guidelines for using our platform.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#08090E] text-[#F1F5F9]">
      {/* Nav */}
      <header className="border-b border-white/[0.06] bg-[#08090E]/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#0EA5E9]/[0.1]">
              <Radar className="h-4 w-4 text-[#0EA5E9]" />
            </div>
            <span className="text-[16px] font-bold tracking-tight">Pentra</span>
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-[14px] font-medium text-[#8B8FA3] transition-colors hover:text-white">
            <ArrowLeft className="h-3.5 w-3.5" /> Back
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-[#8B8FA3]">Last updated: March 5, 2026</p>

        <div className="mt-10 space-y-8 text-[#94A3B8] leading-relaxed [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-[#F1F5F9] [&_h2]:mt-10 [&_h2]:mb-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-1">
          <p>
            These Terms of Service (&quot;Terms&quot;) govern your use of the Pentra platform operated by Pentra (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) at pentra.dev. By using our service, you agree to these Terms.
          </p>

          <h2>1. Service Description</h2>
          <p>Pentra provides an AI-powered SEO content generation platform that automatically researches, writes, fact-checks, and publishes blog articles for your website. Our service includes site crawling, keyword research, article generation, fact-checking, internal linking, hero image generation, and multi-platform publishing.</p>

          <h2>2. Account Registration</h2>
          <p>You must create an account to use Pentra. You are responsible for maintaining the security of your account and for all activities under your account. You must provide accurate and complete information during registration.</p>

          <h2>3. Acceptable Use</h2>
          <p>You agree not to use Pentra to:</p>
          <ul>
            <li>Violate any applicable laws or regulations</li>
            <li>Generate content that is defamatory, obscene, or promotes illegal activity</li>
            <li>Misrepresent AI-generated content as human-written where required by law</li>
            <li>Spam search engines or engage in black-hat SEO practices</li>
            <li>Transmit malware or malicious code</li>
            <li>Attempt to reverse-engineer, decompile, or extract our AI models</li>
            <li>Use the service to generate content for prohibited industries (gambling, weapons, illegal substances)</li>
          </ul>

          <h2>4. Subscription Plans &amp; Billing</h2>
          <p>Pentra offers multiple subscription tiers with varying article limits and site allowances. All plans include access to the full feature set. Billing is processed monthly through our payment provider (Stripe via Clerk). You may cancel your subscription at any time, and it will remain active until the end of the current billing period.</p>
          <p>We reserve the right to change pricing with 30 days&apos; notice. Free tier users receive limited article generation per month at no cost.</p>

          <h2>5. AI-Generated Content</h2>
          <p>Content generated by Pentra is produced by AI models and may contain inaccuracies despite our fact-checking process. While we strive for accuracy:</p>
          <ul>
            <li>You are responsible for reviewing all generated content before publishing</li>
            <li>We do not guarantee that generated content is free from errors or omissions</li>
            <li>Fact-check scores are estimates and not guarantees of accuracy</li>
            <li>You should not rely solely on AI-generated content for medical, legal, or financial advice</li>
          </ul>

          <h2>6. Content Ownership &amp; Intellectual Property</h2>
          <p>You retain ownership of all content generated through Pentra for your websites. We retain ownership of the Pentra platform, including its algorithms, code, and design. You grant us a limited license to process your website data solely for the purpose of providing our services.</p>

          <h2>7. Data &amp; Privacy</h2>
          <p>Your use of Pentra is also governed by our <Link href="/legal/privacy" className="text-[#0EA5E9] hover:underline">Privacy Policy</Link>. By using Pentra, you acknowledge that your website data will be crawled and analyzed by our AI systems to generate content. If you publish content that involves personal data, you are responsible for compliance with applicable data protection laws (GDPR, CCPA, etc.).</p>

          <h2>8. Third-Party Integrations</h2>
          <p>Pentra integrates with third-party services including GitHub, WordPress, and webhook endpoints for publishing. You are responsible for maintaining valid credentials and permissions for these integrations. We are not responsible for issues arising from third-party service outages or changes.</p>

          <h2>9. Service Availability</h2>
          <p>While we strive for high uptime, we do not guarantee uninterrupted service. We may perform maintenance, updates, or experience outages. We will make reasonable efforts to notify you of planned downtime.</p>

          <h2>10. Termination</h2>
          <p>You may delete your account at any time. We may suspend or terminate accounts that violate these Terms. Upon termination, your data will be retained for 30 days before permanent deletion.</p>

          <h2>11. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, Pentra shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities. Our total liability is limited to the amount you paid us in the 12 months preceding the claim.</p>

          <h2>12. Changes to Terms</h2>
          <p>We may update these Terms from time to time. We will notify you of material changes via email or through the service. Continued use of the service after changes constitutes acceptance of the new Terms.</p>

          <h2>13. Governing Law</h2>
          <p>These Terms are governed by the laws of Germany. Any disputes shall be resolved in the courts of Kerpen, Germany.</p>

          <h2>14. Contact Information</h2>
          <p>If you have any questions about these Terms of Service, please contact us:</p>
          <div className="rounded-lg border border-white/[0.06] bg-[#0F1117] p-5 mt-3 text-[14px] space-y-1">
            <p><strong className="text-[#F1F5F9]">Email:</strong> pentrahelp@gmail.com</p>
            <p><strong className="text-[#F1F5F9]">Support:</strong> pentrahelp@gmail.com</p>
            <p><strong className="text-[#F1F5F9]">Phone:</strong> +49 1520 9530880</p>
            <p><strong className="text-[#F1F5F9]">Address:</strong> Pentra Legal Team</p>
            <p>Kerpener Straße 6, 50170 Kerpen, Germany</p>
          </div>
        </div>
      </main>
    </div>
  );
}
